spring.datasource.url=jdbc:postgresql://aws-1-ap-northeast-1.pooler.supabase.com:5432/postgres?sslmode=require&currentSchema=operations_schema
spring.datasource.username=postgres.vggyqelczapthdayxuhx
spring.datasource.password=MTRDM191814_MarcusTheodiosn
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.default_schema=operations_schema
server.port=8082